base_url = "https://maksym-tarnavskyi.github.io"
title = "Maksym Tarnavskyi"
description = "Lead NLP Data Scientist specializing in Generative AI and Machine Learning"
compile_sass = true
minify_html = true
generate_feeds = false
theme = "anemone"

[markdown]
highlight_code = true
external_links_target_blank = true
smart_punctuation = true

[extra]
author = "Maksym Tarnavskyi"
list_pages = false
enable_search = false

header_nav = [
  { url = "/", name_en = "/home/" }
]
